Repository AGH-Narzedzia-Informatyczne-2023-2024/charades-online, pull requests merged in 2023-11, with the labels that each got.

#8 Enter room page
  index.html
  src/App.tsx
  src/components/EnterRoomPage.tsx
Labels: enhancement, important

#10 game-page
  src/App.tsx
  src/components/EnterRoomPage.tsx
  src/components/GamePage.tsx
Labels: enhancement

#11 Make small visual adjustments
  src/components/EnterRoomPage.tsx
Labels: enhancement

#13 add canvas and input to game component
  src/components/GamePage.tsx
Labels: enhancement

#16 Add a section with information about the project
  src/components/EnterRoomPage.tsx
Labels: enhancement, important

#18 Add DrawingMenu component. Adjust canvas styling
  src/components/DrawingMenu.tsx
  src/components/GamePage.tsx
  src/components/PenColorButton.tsx
Labels: enhancement

#20 added How To Play section in footer of main page
  src/components/Dot.tsx
  src/components/EnterRoomPage.tsx
Labels: enhancement

#21 Fix Function type linter error
  src/components/EnterRoomPage.tsx
  src/components/GamePage.tsx
Labels: bug
